import java.util.Arrays;

public class Manacher {

    /**
     * Preprocesses the string by placing '#' between every character, 
     * plus one at the start and end.
     * Example: "aba" -> "#a#b#a#"
     * This transforms both odd and even length palindromes into odd lengths 
     * in the processed string, unifying the logic.
     */
    private static String preProcess(String s) {
        if (s == null || s.isEmpty()) return "";
        
        StringBuilder sb = new StringBuilder("#"); 
        for (int i = 0; i < s.length(); i++) {
            sb.append(s.charAt(i)).append('#');
        }
        return sb.toString();
    }
    
    /**
     * Manacher's Algorithm: Computes palindrome radii for all centers in O(N) time.
     * p[i] stores the radius of the palindrome centered at index i (including character at i).
     */
    private static int[] manacher(String t) {
        int n = t.length();
        int[] p = new int[n];
        
        // Every single character is a palindrome of radius at least 1 (itself)
        Arrays.fill(p, 1);
        
        // (l, r) are the exclusive boundaries of the rightmost palindrome found so far.
        // That means t.substring(l + 1, r) is guaranteed to be a palindrome.
        int l = 0;
        int r = 0;
        
        for (int i = 1; i < n - 1; i++) {
            // STEP 1: Reuse pre-computed information if current index 'i' falls inside (l, r)
            if (i < r) {
                // l + (r - i) calculates the mirror index 'j' on the left side of the current palindrome.
                // We pick min(r - i, p[j]) because our symmetry guarantee ends at boundary 'r'.
                p[i] = Math.min(r - i, p[l + (r - i)]);
            }
            
            // STEP 2: Expand outward starting from our guaranteed radius p[i]
            // If p[i] was set by Case 1 (fully inside), this loop fails immediately in O(1).
            // If p[i] reached boundary 'r', this loop checks unexamined characters past 'r'.
            while (i - p[i] >= 0 && i + p[i] < n && t.charAt(i - p[i]) == t.charAt(i + p[i])) {
                p[i]++;
            }
            
            // STEP 3: Update the rightmost palindrome boundary (l, r) if this palindrome expands past 'r'
            if (i + p[i] > r) {
                l = i - p[i];
                r = i + p[i];
            }
        }
        
        return p;
    }
    
    /**
     * Checks if substring s[l...r] in the original string is a palindrome in O(1) time.
     * @param p The array generated by manacher()
     * @param l Start index in original string (0-indexed)
     * @param r End index in original string (0-indexed, inclusive)
     */
    private static boolean isPalindrome(int[] p, int l, int r) {
        // Formula mapping original substring s[l...r] to its center in the processed string 't'
        int centerInProcessed = l + r + 1;
        
        // The length of the substring s[l...r]
        int requiredLength = r - l + 1;
        
        // In the transformed string, (p[center] - 1) gives the actual maximum 
        // palindrome length centered at 'centerInProcessed'.
        return (p[centerInProcessed] - 1) >= requiredLength;
    }
    
    public static void main(String[] args) {
        String s = "bbabbcbc";
        String processed = preProcess(s);
        int[] p = manacher(processed);
        
        System.out.println("Original String: " + s);
        System.out.println("Processed String: " + processed);
        System.out.println("P Array: " + Arrays.toString(p));
        
        // --- Examples for checking if s[l...r] is a palindrome in O(1) ---
        
        // "bbab" (s[0..3]) -> NOT a palindrome
        System.out.println("Is s[0..3] (\"bbab\") palindrome? " + isPalindrome(p, 0, 3)); 
        
        // "bbabb" (s[0..4]) -> IS a palindrome
        System.out.println("Is s[0..4] (\"bbabb\") palindrome? " + isPalindrome(p, 0, 4)); 
        
        // "bcbc" (s[4..7]) -> NOT a palindrome
        System.out.println("Is s[4..7] (\"bcbc\") palindrome? " + isPalindrome(p, 4, 7));   
        
        // "cbc" (s[5..7]) -> IS a palindrome
        System.out.println("Is s[5..7] (\"cbc\") palindrome? " + isPalindrome(p, 5, 7));   
    }
}
